
name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: MacOs
    steps:
      uses: actions/checkout@v2        
      - run: pip install --upgrade pip
      - run: pip install mkdocs-material
      - run: pip install mkdocs-jupyter
      
      # C'est ici qu'il faut ajouter si besoin
      # les instructions pour installer avec pip
      # les autres plugins MkDocs ou extensions MarkDown
      # souhaités pour le déploiement du site...

      - run: mkdocs gh-deploy --force
